language: rust
matrix:
  fast_finish: true
  include:  
    - name: "trusty / llvm 5.0 / bcc 0.8.0"
      os: linux
      dist: trusty
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="5.0" BCC_VERSION="0.8.0" FEATURES="bcc_v0_8_0"
      script:
        - bash build/ci.sh
    - name: "trusty / llvm 5.0 / bcc 0.9.0"
      os: linux
      dist: trusty
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="5.0" BCC_VERSION="0.9.0" FEATURES="bcc_v0_9_0"
      script:
        - bash build/ci.sh
    - name: "trusty / llvm 5.0 / bcc 0.10.0"
      os: linux
      dist: trusty
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="5.0" BCC_VERSION="0.10.0" FEATURES="bcc_v0_10_0"
      script:
        - bash build/ci.sh
    - name: "xenial / llvm 8 / bcc 0.9.0"
      os: linux
      dist: xenial
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="8" BCC_VERSION="0.9.0" FEATURES="bcc_v0_9_0"
      script:
        - bash build/ci.sh
    - name: "xenial / llvm 8 / bcc 0.10.0"
      os: linux
      dist: xenial
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="8" BCC_VERSION="0.10.0" FEATURES="bcc_v0_10_0"
      script:
        - bash build/ci.sh
    - name: "xenial / llvm 8 / bcc 0.11.0"
      os: linux
      dist: xenial
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="8" BCC_VERSION="0.11.0" FEATURES="bcc_v0_11_0"
      script:
        - bash build/ci.sh
    - name: "xenial / llvm 8 / bcc 0.12.0"
      os: linux
      dist: xenial
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="8" BCC_VERSION="0.12.0" FEATURES="bcc_v0_12_0"
      script:
        - bash build/ci.sh
    - name: "xenial / llvm 8 / bcc latest"
      os: linux
      dist: xenial
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="8" BCC_VERSION="latest"
      script:
        - bash build/ci.sh
    - name: "xenial / llvm 9 / bcc 0.9.0"
      os: linux
      dist: xenial
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="9" BCC_VERSION="0.9.0" FEATURES="bcc_v0_9_0"
      script:
        - bash build/ci.sh
    - name: "xenial / llvm 9 / bcc 0.10.0"
      os: linux
      dist: xenial
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="9" BCC_VERSION="0.10.0" FEATURES="bcc_v0_10_0"
      script:
        - bash build/ci.sh
    - name: "xenial / llvm 9 / bcc 0.11.0"
      os: linux
      dist: xenial
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="9" BCC_VERSION="0.11.0" FEATURES="bcc_v0_11_0"
      script:
        - bash build/ci.sh
    - name: "xenial / llvm 9 / bcc 0.12.0"
      os: linux
      dist: xenial
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="9" BCC_VERSION="0.12.0" FEATURES="bcc_v0_12_0"
      script:
        - bash build/ci.sh
    - name: "xenial / llvm 9 / bcc latest"
      os: linux
      dist: xenial
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="9" BCC_VERSION="latest"
      script:
        - bash build/ci.sh
    - name: "bionic / llvm 8 / bcc 0.9.0"
      os: linux
      dist: bionic
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="8" BCC_VERSION="0.9.0" FEATURES="bcc_v0_9_0"
      script:
        - bash build/ci.sh
    - name: "bionic / llvm 8 / bcc 0.10.0"
      os: linux
      dist: bionic
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="8" BCC_VERSION="0.10.0" FEATURES="bcc_v0_10_0"
      script:
        - bash build/ci.sh
    - name: "bionic / llvm 8 / bcc 0.11.0"
      os: linux
      dist: bionic
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="8" BCC_VERSION="0.11.0" FEATURES="bcc_v0_11_0"
      script:
        - bash build/ci.sh
    - name: "bionic / llvm 8 / bcc 0.12.0"
      os: linux
      dist: bionic
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="8" BCC_VERSION="0.12.0" FEATURES="bcc_v0_12_0"
      script:
        - bash build/ci.sh
    - name: "bionic / llvm 8 / bcc latest"
      os: linux
      dist: bionic
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="8" BCC_VERSION="latest"
      script:
        - bash build/ci.sh
    - name: "bionic / llvm 9 / bcc 0.9.0"
      os: linux
      dist: bionic
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="9" BCC_VERSION="0.9.0" FEATURES="bcc_v0_9_0"
      script:
        - bash build/ci.sh
    - name: "bionic / llvm 9 / bcc 0.10.0"
      os: linux
      dist: bionic
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="9" BCC_VERSION="0.10.0" FEATURES="bcc_v0_10_0"
      script:
        - bash build/ci.sh
    - name: "bionic / llvm 9 / bcc 0.11.0"
      os: linux
      dist: bionic
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="9" BCC_VERSION="0.11.0" FEATURES="bcc_v0_11_0"
      script:
        - bash build/ci.sh
    - name: "bionic / llvm 9 / bcc 0.12.0"
      os: linux
      dist: bionic
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="9" BCC_VERSION="0.12.0" FEATURES="bcc_v0_12_0"
      script:
        - bash build/ci.sh
    - name: "bionic / llvm 9 / bcc latest"
      os: linux
      dist: bionic
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="9" BCC_VERSION="latest"
      script:
        - bash build/ci.sh
    - name: "bionic / llvm 10 / bcc 0.9.0"
      os: linux
      dist: bionic
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="10" BCC_VERSION="0.9.0" FEATURES="bcc_v0_9_0"
      script:
        - bash build/ci.sh
    - name: "bionic / llvm 10 / bcc 0.10.0"
      os: linux
      dist: bionic
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="10" BCC_VERSION="0.10.0" FEATURES="bcc_v0_10_0"
      script:
        - bash build/ci.sh
    - name: "bionic / llvm 10 / bcc 0.11.0"
      os: linux
      dist: bionic
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="10" BCC_VERSION="0.11.0" FEATURES="bcc_v0_11_0"
      script:
        - bash build/ci.sh
    - name: "bionic / llvm 10 / bcc 0.12.0"
      os: linux
      dist: bionic
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="10" BCC_VERSION="0.12.0" FEATURES="bcc_v0_12_0"
      script:
        - bash build/ci.sh
    - name: "bionic / llvm 10 / bcc latest"
      os: linux
      dist: bionic
      rust: stable
      env: RUST_BACKTRACE=1 LLVM_VERSION="10" BCC_VERSION="latest"
      script:
        - bash build/ci.sh
    - name: "shellcheck"
      os: linux
      dist: bionic
      rust: stable
      script:
        - shellcheck build/*.sh

