on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  cache: 0

jobs:
  focal-llvm_9-bcc_v0_12_0:
    name: focal / llvm 9 / bcc 0.12.0
    runs-on: ubuntu-20.04
    env:
      BCC: "0.12.0"
      DIST: focal
      FEATURES: bcc_v0_12_0
      LLVM: 9
    steps:
    - uses: actions/checkout@v2
    - name: Run CI
      run: bash -e build/ci.sh
  focal-llvm_9-bcc_v0_13_0:
    name: focal / llvm 9 / bcc 0.13.0
    runs-on: ubuntu-20.04
    env:
      BCC: "0.13.0"
      DIST: focal
      FEATURES: bcc_v0_13_0
      LLVM: 9
    steps:
    - uses: actions/checkout@v2
    - name: Run CI
      run: bash -e build/ci.sh
  focal-llvm_9-bcc_v0_14_0:
    name: focal / llvm 9 / bcc 0.14.0
    runs-on: ubuntu-20.04
    env:
      BCC: "0.14.0"
      DIST: focal
      FEATURES: bcc_v0_14_0
      LLVM: 9
    steps:
    - uses: actions/checkout@v2
    - name: Run CI
      run: bash -e build/ci.sh
  focal-llvm_9-bcc_v0_15_0:
    name: focal / llvm 9 / bcc 0.15.0
    runs-on: ubuntu-20.04
    env:
      BCC: "0.15.0"
      DIST: focal
      FEATURES: bcc_v0_15_0
      LLVM: 9
    steps:
    - uses: actions/checkout@v2
    - name: Run CI
      run: bash -e build/ci.sh
  focal-llvm_9-bcc_v0_15_0-static:
    name: focal / llvm 9 / bcc 0.15.0 / static
    runs-on: ubuntu-20.04
    env:
      BCC: "0.15.0"
      DIST: focal
      FEATURES: bcc_v0_15_0 static
      LLVM: 9
      STATIC: true
    steps:
    - uses: actions/checkout@v2
    - name: Run CI
      run: bash -e build/ci.sh
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install rustfmt
      run: rustup component add rustfmt
    - name: rustfmt
      run: cargo fmt -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install clippy
      run: rustup component add clippy
    - name: clippy
      run: cargo clippy || cargo clippy
